version: 2

aliases:
  - &restore-cache-src
    key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}-1

  - &save-cache-src
    key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}-1
    paths:
      - node_modules

  - &restore-cache-starters
    keys:
      - dependency-cache-{{ .Branch }}{{ checksum "build/angular-official-blank/package.json" }}-1
      - dependency-cache-{{ .Branch }}{{ checksum "build/angular-official-tabs/package.json" }}-1

  - &save-cache-angular-official-blank
    key: dependency-cache-{{ .Branch }}{{ checksum "build/angular-official-blank/package.json" }}-1
    paths:
      - build/angular-official-blank/node_modules

  - &save-cache-angular-official-tabs
    key: dependency-cache-{{ .Branch }}{{ checksum "build/angular-official-tabs/package.json" }}-1
    paths:
      - build/angular-official-tabs/node_modules

defaults: &defaults
  working_directory: /tmp/workspace
  docker:
    - image: circleci/node:latest-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache: *restore-cache-src
      - run: npm install
      - save_cache: *save-cache-src
      - run: npm run src:lint
      - run: npm run src:build
      - run: npm run starters:build
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache: *restore-cache-starters
      - run: npm run starters:test
      - save_cache: *save-cache-angular-official-blank
      - save_cache: *save-cache-angular-official-tabs
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: npm run starters:deploy -- --tag latest

workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires: [build]
      - deploy:
          requires: [test]
          filters:
            branches:
              only: master
