version: 2

aliases:
  - &install-chrome
      name: Install Chrome
      command: |
        sudo apt install -y libappindicator3-1
        curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome.deb
        sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
        rm google-chrome.deb

  - &restore-cache-src
      key: dependency-cache-{{ checksum "package.json" }}-2

  - &save-cache-src
      key: dependency-cache-{{ checksum "package.json" }}-2
      paths:
        - node_modules

  - &restore-cache-vue-starters
      key: dependency-cache-{{ checksum "starter-checksum-vue.sha256" }}-2

  - &save-cache-vue-starters
      key: dependency-cache-{{ checksum "starter-checksum-vue.sha256" }}-2
      paths:
        - build/vue-official-list/node_modules
        - build/vue-official-blank/node_modules
        - build/vue-official-sidemenu/node_modules
        - build/vue-official-tabs/node_modules
  
  - &restore-cache-react-starters
      key: dependency-cache-{{ checksum "starter-checksum-react.sha256" }}-1

  - &save-cache-react-starters
      key: dependency-cache-{{ checksum "starter-checksum-react.sha256" }}-1
      paths:
        - build/react-official-list/node_modules
        - build/react-official-blank/node_modules
        - build/react-official-sidemenu/node_modules
        - build/react-official-tabs/node_modules

  - &restore-cache-angular-starters
      key: dependency-cache-{{ checksum "starter-checksum-angular.sha256" }}-1

  - &save-cache-angular-starters
      key: dependency-cache-{{ checksum "starter-checksum-angular.sha256" }}-1
      paths:
        - build/angular-official-list/node_modules
        - build/angular-official-blank/node_modules
        - build/angular-official-sidemenu/node_modules
        - build/angular-official-tabs/node_modules

  - &restore-cache-ionic-angular-starters
      key: dependency-cache-{{ checksum "starter-checksum-ionic-angular.sha256" }}-1

  - &save-cache-ionic-angular-starters
      key: dependency-cache-{{ checksum "starter-checksum-ionic-angular.sha256" }}-1
      paths:
        - build/ionic-angular-community-danielsogl-super/node_modules
        - build/ionic-angular-community-ionic-team-example/node_modules
        - build/ionic-angular-community-oktadeveloper-jhipster/node_modules
        - build/ionic-angular-official-aws/node_modules
        - build/ionic-angular-official-blank/node_modules
        - build/ionic-angular-official-sidemenu/node_modules
        - build/ionic-angular-official-super/node_modules
        - build/ionic-angular-official-tabs/node_modules
        - build/ionic-angular-official-tutorial/node_modules

  - &restore-cache-ionic1-starters
      key: dependency-cache-{{ checksum "starter-checksum-ionic1.sha256" }}-1

  - &save-cache-ionic1-starters
      key: dependency-cache-{{ checksum "starter-checksum-ionic1.sha256" }}-1
      paths:
        - build/ionic1-official-blank/node_modules
        - build/ionic1-official-maps/node_modules
        - build/ionic1-official-sidemenu/node_modules
        - build/ionic1-official-tabs/node_modules

defaults: &defaults
  working_directory: /tmp/workspace
  docker:
    - image: circleci/node:10-browsers

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache: *restore-cache-src
      - run: npm install
      - save_cache: *save-cache-src
      - run: npm run src:lint
      - run: npm run src:build
      - run: rm -rf node_modules/@types
      - run: npm run starters:find-redundant
      - run: npm run starters:build
      - run: npm run starters:generate-checksum
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - "*"
            
  test_vue:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache: *restore-cache-vue-starters
      - run: npm run starters:test -- --type=vue
      - save_cache: *save-cache-vue-starters

  test_react:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache: *restore-cache-react-starters
      - run: npm run starters:test -- --type=react
      - save_cache: *save-cache-react-starters

  test_angular:
    <<: *defaults
    steps:
      - run: *install-chrome
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache: *restore-cache-angular-starters
      # - run: npm run starters:test -- --type=angular
      - save_cache: *save-cache-angular-starters

  test_ionic_angular:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache: *restore-cache-ionic-angular-starters
      - run: npm run starters:test -- --type=ionic-angular
      - save_cache: *save-cache-ionic-angular-starters

  test_ionic1:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - restore_cache: *restore-cache-ionic1-starters
      - run: npm run starters:test -- --type=ionic1
      - save_cache: *save-cache-ionic1-starters

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: npm run starters:deploy -- --tag latest

workflows:
  version: 2
  build:
    jobs:
      - build
      - test_vue:
          requires:
            - build
      - test_react:
          requires:
            - build
      - test_angular:
          requires:
            - build
      - test_ionic_angular:
          requires:
            - build
      - test_ionic1:
          requires:
            - build
      - deploy:
          requires:
            - test_vue
            - test_react
            - test_angular
            - test_ionic_angular
            - test_ionic1
          filters:
            branches:
              only: main
